# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Template-Plugin-Pagination
version:      0.10
version_from: lib/Template/Plugin/Pagination.pm
installdirs:  site
requires:
    Data::Paginated:               1.00
    Template:                      2.07

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
